const products = [
    // 🍎 Fruits
    {
        id: 1,
        name: "Red Apples",
        category: "Fruits",
        price: 120,
        badge: "New",
        image: "/img/Fruits/apple-1.jpeg",
      },
      {
        id: 2,
        name: "Green Apples",
        category: "Fruits",
        price: 125,
        badge: "New",
        image: "/img/Fruits/apple-2.jpeg",
      },
      {
        id: 3,
        name: "Golden Apples",
        category: "Fruits",
        price: 130,
        badge: "Sale",
        image: "/img/Fruits/apple-3.jpeg",
      },
      {
        id: 4,
        name: "Yellow Bananas",
        category: "Fruits",
        price: 60,
        badge: "New",
        image: "/img/Fruits/banana-1.jpeg",
      },
      {
        id: 5,
        name: "Fresh Bananas",
        category: "Fruits",
        price: 58,
        badge: "Sale",
        image: "/img/Fruits/banana-2.jpeg",
      },
      {
        id: 6,
        name: "Black Grapes",
        category: "Fruits",
        price: 90,
        badge: "New",
        image: "/img/Fruits/black-grape.jpeg",
      },
      {
        id: 7,
        name: "Green Grapes",
        category: "Fruits",
        price: 95,
        badge: "Sale",
        image: "/img/Fruits/greengrape.jpeg",
      },
      {
        id: 8,
        name: "Juicy Lemons",
        category: "Fruits",
        price: 40,
        badge: "New",
        image: "/img/Fruits/lemon.jpeg",
      },
      {
        id: 9,
        name: "Sweet Mangoes",
        category: "Fruits",
        price: 150,
        badge: "New",
        image: "/img/Fruits/mango2ß.jpeg",
      },
      {
        id: 10,
        name: "Ripe Mangoes",
        category: "Fruits",
        price: 155,
        badge: "Sale",
        image: "/img/Fruits/mango2.jpeg",
      },
  
    // 🥦 Vegetables
    {
      id: 11,
      name: "Carrots",
      category: "Grains",
      price: 40,
      badge: "Fresh",
      image: "",
    },
    {
      id: 12,
      name: "Broccoli",
      category: "Vegetables",
      price: 60,
      badge: "Organic",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 13,
      name: "Spinach",
      category: "Vegetables",
      price: 30,
      badge: "Healthy",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 14,
      name: "Tomatoes",
      category: "Vegetables",
      price: 50,
      badge: "Ripe",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 15,
      name: "Potatoes",
      category: "Vegetables",
      price: 35,
      badge: "Sale",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 16,
      name: "Onions",
      category: "Vegetables",
      price: 45,
      badge: "Fresh",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 17,
      name: "Bell Peppers",
      category: "Vegetables",
      price: 70,
      badge: "Colorful",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 18,
      name: "Cucumbers",
      category: "Vegetables",
      price: 40,
      badge: "Cool",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 19,
      name: "Eggplants",
      category: "Vegetables",
      price: 55,
      badge: "Fresh",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
    {
      id: 20,
      name: "Lettuce",
      category: "Vegetables",
      price: 25,
      badge: "Crisp",
      image: "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    },
  
    // 🥜 Dry Fruits
    {
      id: 21,
      name: "Almonds",
      category: "Dry Fruits",
      price: 500,
      badge: "Healthy",
      image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
    },
    {
      id: 22,
      name: "Cashews",
      category: "Dry Fruits",
      price: 600,
      badge: "Tasty",
      image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
    },
    {
      id: 23,
      name: "Walnuts",
      category: "Dry Fruits",
      price: 550,
      badge: "Organic",
      image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
    },
    {
      id: 24,
      name: "Raisins",
      category: "Dry Fruits",
      price: 300,
      badge: "Sweet",
      image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
    },
    {
        id: 25,
        name: "Pistachios",
        category: "Dry Fruits",
        price: 650,
        badge: "Salted",
        image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
      },
      {
        id: 26,
        name: "Dates",
        category: "Dry Fruits",
        price: 400,
        badge: "Fresh",
        image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
      },
      {
        id: 27,
        name: "Figs",
        category: "Dry Fruits",
        price: 450,
        badge: "Natural",
        image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
      },
      {
        id: 28,
        name: "Hazelnuts",
        category: "Dry Fruits",
        price: 700,
        badge: "Crunchy",
        image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
      },
      {
        id: 29,
        name: "Apricots (Dried)",
        category: "Dry Fruits",
        price: 480,
        badge: "Sweet",
        image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
      },
      {
        id: 30,
        name: "Mixed Dry Fruits Pack",
        category: "Dry Fruits",
        price: 950,
        badge: "Best Seller",
        image: "https://images.pexels.com/photos/102104/pexels-photo-102104.jpeg",
      },
    
      // 🧪 Fertilizers
      {
        id: 31,
        name: "Organic Compost",
        category: "Fertilizers",
        price: 150,
        badge: "Eco",
        image: "https://images.pexels.com/photos/4221992/pexels-photo-4221992.jpeg",
      },
      {
        id: 32,
        name: "Urea Fertilizer",
        category: "Fertilizers",
        price: 200,
        badge: "Popular",
        image: "https://images.pexels.com/photos/4207902/pexels-photo-4207902.jpeg",
      },
      {
        id: 33,
        name: "DAP Fertilizer",
        category: "Fertilizers",
        price: 250,
        badge: "Effective",
        image: "https://images.pexels.com/photos/4207902/pexels-photo-4207902.jpeg",
      },
      {
        id: 34,
        name: "NPK Fertilizer",
        category: "Fertilizers",
        price: 270,
        badge: "Balanced",
        image: "https://images.pexels.com/photos/4207902/pexels-photo-4207902.jpeg",
      },
      {
        id: 35,
        name: "Sun-dried Figs",
        category: "Dry Fruits",
        price: 360,
        image: "https://images.pexels.com/photos/5945905/pexels-photo-5945905.jpeg",
        badge: "New",
      },
      {
        id: 36,
        name: "Organic Walnuts",
        category: "Dry Fruits",
        price: 460,
        image: "https://images.pexels.com/photos/5945906/pexels-photo-5945906.jpeg",
        badge: "Sale",
      },
      {
        id: 37,
        name: "Peanuts",
        category: "Dry Fruits",
        price: 180,
        image: "https://images.pexels.com/photos/5945904/pexels-photo-5945904.jpeg",
        badge: "New",
      },
      {
        id: 38,
        name: "Cashews",
        category: "Dry Fruits",
        price: 500,
        image: "https://images.pexels.com/photos/5945908/pexels-photo-5945908.jpeg",
        badge: "Sale",
      },
      {
        id: 39,
        name: "Organic Pistachios",
        category: "Dry Fruits",
        price: 520,
        image: "https://images.pexels.com/photos/5945909/pexels-photo-5945909.jpeg",
        badge: "New",
      },
      {
        id: 40,
        name: "Urea Fertilizer",
        category: "Fertilizer",
        price: 220,
        image: "https://images.pexels.com/photos/6165119/pexels-photo-6165119.jpeg",
        badge: "Sale",
      },
      {
        id: 41,
        name: "DAP Fertilizer",
        category: "Fertilizer",
        price: 300,
        image: "https://images.pexels.com/photos/2165681/pexels-photo-2165681.jpeg",
        badge: "New",
      },
      {
        id: 42,
        name: "Compost Fertilizer",
        category: "Fertilizer",
        price: 150,
        image: "https://images.pexels.com/photos/5849878/pexels-photo-5849878.jpeg",
        badge: "Sale",
      },
      {
        id: 43,
        name: "Cow Dung Fertilizer",
        category: "Fertilizer",
        price: 110,
        image: "https://images.pexels.com/photos/6759513/pexels-photo-6759513.jpeg",
        badge: "New",
      },
      {
        id: 44,
        name: "Vermicompost",
        category: "Fertilizer",
        price: 180,
        image: "https://images.pexels.com/photos/5849881/pexels-photo-5849881.jpeg",
        badge: "Sale",
      },
      {
        id: 45,
        name: "Tomatoes",
        category: "Vegetables",
        price: 50,
        image: "https://images.pexels.com/photos/1300975/pexels-photo-1300975.jpeg",
        badge: "New",
      },
      {
        id: 46,
        name: "Broccoli",
        category: "Vegetables",
        price: 70,
        image: "https://images.pexels.com/photos/2518794/pexels-photo-2518794.jpeg",
        badge: "Sale",
      },
      {
        id: 47,
        name: "Cauliflower",
        category: "Vegetables",
        price: 55,
        image: "https://images.pexels.com/photos/1192053/pexels-photo-1192053.jpeg",
        badge: "New",
      },
      {
        id: 48,
        name: "Eggplant",
        category: "Vegetables",
        price: 45,
        image: "https://images.pexels.com/photos/5946281/pexels-photo-5946281.jpeg",
        badge: "Sale",
      },
      {
        id: 49,
        name: "Red Onions",
        category: "Vegetables",
        price: 35,
        image: "https://images.pexels.com/photos/42059/onion-vegetables-red-food-42059.jpeg",
        badge: "New",
      },
      {
        id: 50,
        name: "Sweet Corn",
        category: "Vegetables",
        price: 60,
        image: "https://images.pexels.com/photos/697244/pexels-photo-697244.jpeg",
        badge: "Sale",
      },
    ];

    export default products;